file = open('planets.txt', 'a',encoding='utf-8')
file.write('Mercury\n')
file.write('Venus\n')
file.write('Earth\n')
file.write('Mars\n')
file.write('Jupiter\n')
file.write('Saturn\n')
file.write('Uranus\n')
file.write('Neptune\n')
file.close()
